package com.example.vidyatracker11;

import javafx.scene.Scene;
import javafx.stage.Modality;
import javafx.stage.Stage;

public abstract class PlayedAddEditGoal extends AddEditGoal{
    //Fields
    PlayedGameFilter filter;

    public PlayedAddEditGoal(){
        //Count games meeting requirements and set start progress to count
        enterCurrentStartProgress.setOnAction(e -> progressStartBox.setText("" + filter.filteredList().size()));

        //Count games meeting requirements and set goal progress to count
        enterCurrentGoalProgress.setOnAction(e -> progressGoalBox.setText("" + filter.filteredList().size()));

        filterButton.setOnAction(e -> {
            //Open window to manage fiters
            //Local variables
            Stage stage = new Stage();
            PlayedGoalFilterWindow playedGoalFilterWindow = new PlayedGoalFilterWindow(filter);
            Scene scene = new Scene(playedGoalFilterWindow);

            //GUI
            stage.getIcons().add(ApplicationGUI.icon);
            stage.setResizable(false);
            stage.setScene(scene);
            stage.setTitle("Add New Played Game");
            stage.initModality(Modality.APPLICATION_MODAL);
            scene.getStylesheets().add(ApplicationGUI.styleSheet);

            playedGoalFilterWindow.confirmButton.setOnAction(e1 -> {
                //Set current filter to filter generated by playedGoalFilterWindow
                playedGoalFilterWindow.setFilters();
                filter = playedGoalFilterWindow.getFilter();
            });

            stage.show();
        });
    }
}
