package com.example.vidyatracker11;

import javafx.scene.Scene;
import javafx.stage.Modality;
import javafx.stage.Stage;

public abstract class UnplayedAddEditGoal extends AddEditGoal{
    //Fields
    UnplayedGameFilter filter;

    public UnplayedAddEditGoal(){
        //Count games meeting requirements and set start progress to count
        enterCurrentStartProgress.setOnAction(e -> progressStartBox.setText("" + filter.filteredList().size()));

        //Count games meeting requirements and set goal progress to count
        enterCurrentGoalProgress.setOnAction(e -> progressGoalBox.setText("" + filter.filteredList().size()));

        filterButton.setOnAction(e -> {
            //Open window to manage fiters
            //Local variables
            Stage stage = new Stage();
            UnplayedGoalFilterWindow unplayedGoalFilterWindow = new UnplayedGoalFilterWindow(filter);
            Scene scene = new Scene(unplayedGoalFilterWindow);

            //GUI
            stage.getIcons().add(ApplicationGUI.icon);
            stage.setResizable(false);
            stage.setScene(scene);
            stage.setTitle("Add New Played Game");
            stage.initModality(Modality.APPLICATION_MODAL);
            scene.getStylesheets().add(ApplicationGUI.styleSheet);

            unplayedGoalFilterWindow.confirmButton.setOnAction(e1 -> {
                //Set current filter to filter generated by playedGoalFilterWindow
                unplayedGoalFilterWindow.setFilters();
                filter = unplayedGoalFilterWindow.getFilter();
            });

            stage.show();
        });
    }
}
